## OR

단층 perceptron을 이용하여 다음의 데이터를 분류하여라.

In [36]:
import numpy as np
X = [[0,0],[1,0],[0,1],[1,1]] # input
t = [0,1,1,1] # 실제값
# y 예측값

In [37]:
w, b=[0,0], 0
eta = 0.1

In [38]:
def perc(x):
    f=np.dot(w,x)+b
    if f>=0:
        y=1
    else:
        y=0
    return y

In [39]:
for n in range(1000):
    for i in range(4):
        error = t[i]- perc(X[i])
        w[0] = w[0] + eta * error * X[i][0]
        w[1] = w[1] + eta * error * X[i][1]
        b = b + eta * error
    
w,b

([0.1, 0.1], -0.1)

In [40]:
perc(X[0]),perc(X[1]),perc(X[2]),perc(X[3])

(0, 1, 1, 1)

## Iris classifications

단층 perceptron을 이용하여 다음의 데이터를 분류하여라.

In [41]:
import numpy as np
import matplotlib.pyplot as plt

In [42]:
from sklearn import datasets
iris = datasets.load_iris() # 분꽃
iris.target_names # 3종류의 분꽃 분류하기
iris.feature_names # features

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [43]:
X=iris.data # input data # the number of input nodes = 4

In [44]:
iris.target_names # setosa = 0, not setosa = 1

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [45]:
y=np.where(iris.target>0,1,0) # 0(setosa) 과 1(setosa 외) 로 분류


위의 데이터를 단층 perceptron을 이용하여 분류하는 신경망을 만들고 학습하여라.
입력층의 노드는 바이어스를 제외하고 4개로 한다. 바이어스 1개를 포함 총 5개이다.
출력층의 노드는 1개로 한다.

In [46]:
x=(X[0],X[1],X[2],X[3])
x,t

((array([5.1, 3.5, 1.4, 0.2]),
  array([4.9, 3. , 1.4, 0.2]),
  array([4.7, 3.2, 1.3, 0.2]),
  array([4.6, 3.1, 1.5, 0.2])),
 [0, 1, 1, 1])

In [47]:
w,b=[0,0,0,0],1
eta=0.1
perc(X[0]),perc(X[1]),perc(X[2]),perc(X[3]),t

(1, 1, 1, 1, [0, 1, 1, 1])

In [48]:
for i in range(4):
    error = t[i]-perc(X[i])
    print(error)

-1
0
0
0


In [49]:
for n in range(100):
    error_sum=0
    for i in range(4):
        error = t[i]-perc(X[i])
        error_sum=error_sum+abs(error)
        
        w[0]=w[0]+eta*error*X[i][0]
        w[1]=w[1]+eta*error*X[i][1]
        w[2]=w[2]+eta*error*X[i][2]
        w[3]=w[3]+eta*error*X[i][3]
        b=b+eta*error
        
    if(error_sum==0):
        break
        
w,b

([0.5100000000000007, -1.2900000000000011, 0.39, 0.06000000000000001],
 1.3000000000000003)